const { ipcMain } = require('electron');
const fs = require('fs');
const path = require('path');

function registerExportHandlers() {
  ipcMain.handle('export-game', async (event, projectData, outputPath) => {
    if (!projectData.filePath) {
      throw new Error('Project must be saved before exporting');
    }

    const projectDir = path.dirname(projectData.filePath);

    // 1. Create output directory structure
    const dirs = [
      outputPath,
      path.join(outputPath, 'engine'),
      path.join(outputPath, 'assets'),
      path.join(outputPath, 'assets', 'sprites'),
      path.join(outputPath, 'assets', 'audio')
    ];

    for (const dir of dirs) {
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
    }

    // 2. Copy engine from project's local engine/ folder
    const projectEngineDir = path.join(projectDir, 'engine');
    copyDirRecursive(projectEngineDir, path.join(outputPath, 'engine'));

    // 3. Copy project assets
    const projectAssetsDir = path.join(projectDir, 'assets');
    if (fs.existsSync(projectAssetsDir)) {
      copyDirRecursive(projectAssetsDir, path.join(outputPath, 'assets'));
    }

    // 3b. Copy custom script files
    if (projectData.scripts && projectData.scripts.length > 0) {
      const scriptsOutDir = path.join(outputPath, 'scripts');
      if (!fs.existsSync(scriptsOutDir)) {
        fs.mkdirSync(scriptsOutDir, { recursive: true });
      }
      for (const s of projectData.scripts) {
        const srcFile = path.join(projectDir, 'scripts', s.filename);
        if (fs.existsSync(srcFile)) {
          fs.copyFileSync(srcFile, path.join(scriptsOutDir, s.filename));
        }
      }
    }

    // 4. Generate game.js
    const gameJs = generateGameJs(projectData);
    fs.writeFileSync(path.join(outputPath, 'game.js'), gameJs, 'utf-8');

    // 4b. Generate _sounds.js (base64 audio cache)
    const soundsJs = generateSoundsJs(projectDir);
    if (soundsJs) {
      fs.writeFileSync(path.join(outputPath, '_sounds.js'), soundsJs, 'utf-8');
    }

    // 5. Generate index.html
    const indexHtml = generateIndexHtml(projectData);
    fs.writeFileSync(path.join(outputPath, 'index.html'), indexHtml, 'utf-8');

    return true;
  });
}

function copyDirRecursive(src, dest) {
  if (!fs.existsSync(src)) return;
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }

  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      copyDirRecursive(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

function generateIndexHtml(project) {
  const settings = project.settings || {};
  const w = settings.canvasWidth || 960;
  const h = settings.canvasHeight || 540;
  const bg = settings.backgroundColor || '#0a0a1a';

  // Build loader file list (_sounds.js + custom scripts + game.js)
  let loaderFiles = '';
  const hasAudio = project.assets && project.assets.audio && project.assets.audio.length > 0;
  if (hasAudio) {
    loaderFiles += `\n      { name: "_sounds", path: "_sounds.js" },`;
  }
  if (project.scripts && project.scripts.length > 0) {
    for (const s of project.scripts) {
      loaderFiles += `\n      { name: "${s.filename}", path: "scripts/${s.filename}" },`;
    }
  }
  loaderFiles += `\n      { name: "game", path: "game.js" }`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${project.name || 'JCGE Game'}</title>
  <style>
    * { margin: 0; padding: 0; }
    body { background: ${bg}; display: flex; justify-content: center; align-items: center; min-height: 100vh; }
    canvas { display: block; }
  </style>
</head>
<body>
  <canvas id="gameCanvas" width="${w}" height="${h}"></canvas>
  <script src="engine/engine-core.js"></script>
  <script src="engine/game-loader.js"></script>
  <script>
    loader([${loaderFiles}
    ]);
  </script>
</body>
</html>`;
}

function generateGameJs(project) {
  const settings = project.settings || {};
  const scenes = project.scenes || [];
  let code = '// Generated by JCGE Editor\n\n';

  // Generate scene classes
  for (const scene of scenes) {
    code += generateSceneClass(scene, settings) + '\n\n';
  }

  // Generate bootstrap (gameReady fires after loader() loads all scripts)
  code += `// ── Engine Bootstrap ──\n`;
  code += `window.addEventListener('gameReady', function() {\n`;
  code += `  var canvas = document.getElementById('gameCanvas');\n`;
  code += `  var engine = new Engine(canvas);\n`;
  code += `  engine.setCanvasSize(${settings.canvasWidth || 960}, ${settings.canvasHeight || 540});\n`;

  if (settings.displayFPS) {
    code += `  engine.displayFPS = true;\n`;
  }

  // Register scenes
  for (const scene of scenes) {
    const className = sanitizeClassName(scene.name);
    code += `  engine.registerScene(new ${className}('${scene.name}', engine));\n`;
  }

  code += `  engine.start();\n`;
  code += `});\n`;

  return code;
}

function generateSceneClass(scene, settings) {
  const className = sanitizeClassName(scene.name);
  let code = `class ${className} extends Scene {\n`;
  code += `  OnCreate() {\n`;
  code += `    var engine = this.engine;\n`;

  // Camera
  if (scene.camera) {
    const cam = scene.camera;
    if (cam.type === 'world') {
      code += `    var camera = new WorldCamera(${cam.screenWidth || settings.canvasWidth || 960}, ${cam.screenHeight || settings.canvasHeight || 540}, ${cam.levelWidth || 2000}, ${cam.levelHeight || 1200}, ${cam.speed || 10});\n`;
      if (cam.smoothFollow !== undefined) code += `    camera.smoothFollow = ${cam.smoothFollow};\n`;
      if (cam.followLerp !== undefined) code += `    camera.followLerp = ${cam.followLerp};\n`;
      if (cam.zoom !== undefined) code += `    camera._zoom = ${cam.zoom};\n`;
    } else {
      code += `    var camera = new Camera(${cam.screenWidth || settings.canvasWidth || 960}, ${cam.screenHeight || settings.canvasHeight || 540}, ${cam.levelWidth || cam.screenWidth || 960}, ${cam.levelHeight || cam.screenHeight || 540}, ${cam.speed || 10});\n`;
    }
    if (cam.addOffset) code += `    camera.addOffset = true;\n`;
    if (cam.position && (cam.position.X !== 0 || cam.position.Y !== 0)) {
      code += `    camera.position = new Vec2(${cam.position.X}, ${cam.position.Y});\n`;
    }
    code += `    camera.getOffset();\n`;
    code += `    this.setCamera(camera);\n\n`;
  }

  // Layers and objects
  for (let i = 0; i < scene.layers.length; i++) {
    const layer = scene.layers[i];
    const layerVar = 'layer' + i;

    if (layer.isUI) {
      code += `    var ${layerVar} = new UILayer('${layer.name}');\n`;
      code += `    this.registerLayer(${layerVar});\n`;
    } else if (i === 0 && layer.name === 'ground') {
      // ground layer is created by default
      code += `    var ${layerVar} = this.layers[0].layer;\n`;
    } else {
      code += `    var ${layerVar} = new Layer('${layer.name}');\n`;
      code += `    this.registerLayer(${layerVar});\n`;
    }

    // Game objects
    for (let j = 0; j < layer.gameObjects.length; j++) {
      const obj = layer.gameObjects[j];
      const objVar = 'obj_' + sanitizeVarName(obj.name || 'go') + '_' + j;
      code += generateGameObjectCode(objVar, obj, layerVar);
    }

    // Elements
    for (let j = 0; j < layer.elements.length; j++) {
      const el = layer.elements[j];
      const elVar = 'el_' + sanitizeVarName(el.name || 'el') + '_' + j;
      code += generateElementCode(elVar, el, layerVar);
    }

    code += '\n';
  }

  // User onCreate script (runs after visual setup)
  if (scene.script && scene.script.onCreate && scene.script.onCreate.trim()) {
    code += `    // -- User script (onCreate) --\n`;
    code += `    ${scene.script.onCreate.split('\n').join('\n    ')}\n`;
  }

  code += `  }\n\n`;

  // findByName helper
  code += `  findByName(name) {\n`;
  code += `    for (var i = 0; i < this.layers.length; i++) {\n`;
  code += `      var layer = this.layers[i].layer;\n`;
  code += `      for (var j = 0; j < layer.gameObjects.length; j++) {\n`;
  code += `        if (layer.gameObjects[j].name === name) return layer.gameObjects[j];\n`;
  code += `      }\n`;
  code += `      for (var j = 0; j < layer.elements.length; j++) {\n`;
  code += `        if (layer.elements[j].name === name) return layer.elements[j];\n`;
  code += `      }\n`;
  code += `    }\n`;
  code += `    return null;\n`;
  code += `  }\n\n`;

  code += `  OnUpdate(elapsedTime) {\n`;
  code += `    var engine = this.engine;\n`;
  if (scene.script && scene.script.onUpdate && scene.script.onUpdate.trim()) {
    code += `    // -- User script --\n`;
    code += `    ${scene.script.onUpdate.split('\n').join('\n    ')}\n`;
  }
  code += `    return true;\n`;
  code += `  }\n\n`;

  code += `  OnDestroy() {\n`;
  code += `    var engine = this.engine;\n`;
  if (scene.script && scene.script.onDestroy && scene.script.onDestroy.trim()) {
    code += `    // -- User script --\n`;
    code += `    ${scene.script.onDestroy.split('\n').join('\n    ')}\n`;
  }
  code += `    return true;\n`;
  code += `  }\n`;
  code += `}\n`;

  return code;
}

function generateGameObjectCode(varName, obj, layerVar) {
  let code = '';

  if (obj.sprite && obj.sprite.path) {
    if (obj.sprite.type === 'spritesheet') {
      code += `    var ${varName}_sprite = new SpriteSheet('${obj.sprite.name || 'anim'}', ${obj.sprite.width}, ${obj.sprite.height}, ${obj.sprite.frameSpeed || 6}, ${obj.sprite.startFrame || 0}, ${obj.sprite.endFrame || 0}, '${obj.sprite.path}');\n`;
    } else {
      code += `    var ${varName}_sprite = new Sprite(${obj.sprite.width || 32}, ${obj.sprite.height || 32}, '${obj.sprite.path}');\n`;
    }
  } else {
    code += `    var ${varName}_sprite = new Sprite(${obj.sprite ? obj.sprite.width : 32}, ${obj.sprite ? obj.sprite.height : 32}, null);\n`;
  }

  code += `    var ${varName} = new GameObject(${varName}_sprite, new Vec2(${obj.position.X}, ${obj.position.Y}), ${obj.opacity !== undefined ? obj.opacity : 1});\n`;
  code += `    ${varName}.name = '${obj.name || 'GameObject'}';\n`;

  if (obj.isStatic) code += `    ${varName}.staticObject();\n`;
  if (obj.showIt === false) code += `    ${varName}.hide();\n`;
  if (obj.velocity && (obj.velocity.X !== 0 || obj.velocity.Y !== 0)) {
    code += `    ${varName}.velocity = new Vec2(${obj.velocity.X}, ${obj.velocity.Y});\n`;
  }

  code += `    ${layerVar}.registerGameObject(${varName});\n`;
  return code;
}

function generateElementCode(varName, el, layerVar) {
  let code = '';

  // Handle different element types
  if (el.type === 'uiLabel') {
    code += `    var ${varName} = new UILabel('${el.text || ''}', new Vec2(${el.position.X}, ${el.position.Y}), ${el.fontSize || 16});\n`;
    code += `    ${layerVar}.registerElement(${varName});\n`;
    return code;
  }

  if (el.type === 'uiButton') {
    code += `    var ${varName} = new UIButton('${el.label || 'Button'}', new Vec2(${el.position.X}, ${el.position.Y}), new Size(${el.size ? el.size.width : 120}, ${el.size ? el.size.height : 40}), '${el.normalColor || '#333'}', '${el.fillColor || '#555'}', '${el.borderColor || '#888'}');\n`;
    code += `    ${layerVar}.registerElement(${varName});\n`;
    return code;
  }

  if (el.type === 'uiPanel') {
    code += `    var ${varName} = new UIPanel(new Vec2(${el.position.X}, ${el.position.Y}), new Size(${el.size ? el.size.width : 200}, ${el.size ? el.size.height : 150}), '${el.fillColor || 'rgba(0,0,0,0.5)'}', '${el.borderColor || '#888'}');\n`;
    code += `    ${layerVar}.registerElement(${varName});\n`;
    return code;
  }

  // Default element
  if (el.sprite && el.sprite.path) {
    code += `    var ${varName}_sprite = new Sprite(${el.sprite.width || 32}, ${el.sprite.height || 32}, '${el.sprite.path}');\n`;
  } else {
    code += `    var ${varName}_sprite = new Sprite(${el.sprite ? el.sprite.width : 32}, ${el.sprite ? el.sprite.height : 32}, null);\n`;
  }
  code += `    var ${varName} = new Element(${varName}_sprite, new Vec2(${el.position.X}, ${el.position.Y}), ${el.opacity !== undefined ? el.opacity : 1});\n`;
  if (el.showIt === false) code += `    ${varName}.hide();\n`;
  code += `    ${layerVar}.registerElement(${varName});\n`;
  return code;
}

function sanitizeClassName(name) {
  return name.replace(/[^a-zA-Z0-9]/g, '_').replace(/^[0-9]/, '_$&');
}

function sanitizeVarName(name) {
  return name.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
}

function generateSoundsJs(projectDir) {
  const audioDir = path.join(projectDir, 'assets', 'audio');
  if (!fs.existsSync(audioDir)) return null;

  const files = fs.readdirSync(audioDir).filter(f => /\.(mp3|wav|ogg)$/i.test(f));
  if (files.length === 0) return null;

  const mimeMap = { 'mp3': 'audio/mpeg', 'wav': 'audio/wav', 'ogg': 'audio/ogg' };

  let entries = '';
  for (const filename of files) {
    const filePath = path.join(audioDir, filename);
    const buf = fs.readFileSync(filePath);
    const base64 = buf.toString('base64');
    const ext = filename.split('.').pop().toLowerCase();
    const mime = mimeMap[ext] || 'audio/mpeg';
    entries += `  'assets/audio/${filename}': 'data:${mime};base64,${base64}',\n`;
  }

  return `// Audio cache generated by JCGE Editor\nvar AUDIO_CACHE = {\n${entries}};\n\n(function() {\n  var _OrigAudio = window.Audio;\n  window.Audio = function(src) {\n    return new _OrigAudio((AUDIO_CACHE && AUDIO_CACHE[src]) ? AUDIO_CACHE[src] : src);\n  };\n  window.Audio.prototype = _OrigAudio.prototype;\n})();\n`;
}

module.exports = { registerExportHandlers };
